export const PRODUCT_QUERY = `
query{
  products{
   data{
     attributes{
       title
       description
       type
       image{
         data{
           attributes{
             formats
           }
         }
       }
       slug
       price
       image2{
         data{
           attributes{
             formats
           }
         }
       }
       isNew
       categories{
         data{
           attributes{
             title
             description
             image{
               data{
                 attributes{
                   formats
                 }
               }
             }
           }
         }
       }
       sub_categories{
         data{
          id
           attributes{
             title
           }
         }
       }
     }
   }
 }
 subCategories{
  data{
    id
    attributes{
      title
    }
  }
}
}
`;

export const GET_PRODUCT_BY_SUBCATEGORY = `
query{
  products(filters: {sub_categories: {id: {in: [1, 2, 3]}}}){
    data{
      id
      attributes{
        title
        image{
          data{
            attributes{
              formats
            }
          }
        }
        price
    		slug
      }
    }
  }
}
`;

export const GET_PRODUCT_QUERY = `

query getProduct($slug:String!){
  products(filters: {slug:{eq: $slug}}){
    data{
      attributes{
        title, 
        slug, 
        description, 
        price, 
        image{
          data{
            attributes{
              formats
            }
          }
        }
      }
    }
  }
}
`;
