import Head from "next/head";
import { useQuery } from "urql";
import Carousel from "../components/Carousel/Carousel";

import Product from "../components/Product";
import Subscribe from "../components/Subscribe";
import { PRODUCT_QUERY } from "../lib/query";
import { Gallery } from "../styles/Gallery";

export default function Home() {
  const [results] = useQuery({ query: PRODUCT_QUERY });
  const { data, fetching, error } = results;

  if (fetching) return <p>Loading...</p>;
  if (error) return <p>Oh no...{error.message}</p>;

  const products = data.products.data;
  return (
    <div>
      <Head>
        <title>fullstack-E-commerce</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <Carousel />
        <Gallery>
          {products.map((product) => (
            <Product key={product.attributes.slug} product={product} />
          ))}
        </Gallery>
        <Subscribe />
      </main>
    </div>
  );
}
