import Head from "next/head";
import { useQuery } from "urql";
import Carousel from "../components/Carousel/Carousel";
import CategoryFirst from "../components/CategoryFirst";
import FeaturedProducts from "../components/FeaturedProducts";
// import { client, ssrCache } from "../lib/urqlClient";

// import Product from "../components/Product";
import Subscribe from "../components/Subscribe";
import { PRODUCT_QUERY } from "../lib/query";

export default function Home() {
  const [results] = useQuery({ query: PRODUCT_QUERY });
  const { data, fetching, error } = results;

  if (fetching) return <p>Loading...</p>;
  if (error) return <p>Oh no...{error.message}</p>;

  const products = data.products.data;
  console.log(products);
  return (
    <div>
      <Head>
        <title>fullstack-E-commerce</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <Carousel />
        <FeaturedProducts type="featured" product={products} />
        <CategoryFirst />
        <FeaturedProducts type="trending" product={products} />
        <Subscribe />
      </main>
    </div>
  );
}

// export async function getServerSideProps() {
//   await client.query(PRODUCT_QUERY).toPromise();

//   return {
//     props: {
//       urqlState: ssrCache.extractData(),
//     },
//   };
// }
